services:
  node-1:
    build: ./test/fake_host
    privileged: true          # required by dind
    ports:
      - "2201:22"
  node-2:
    build: ./test/fake_host
    privileged: true
    ports:
      - "2202:22"
