require "test_helper"
require "timeout"

# These tests treat "validating a submitted private key" as an attack: SshKeyValidator
# exists because net-ssh parsing a private key may reach OpenSSL/bcrypt, and how long a
# real decrypt/KDF attempt takes is determined by attacker-controlled fields in the key
# (bcrypt rounds, PKCS#8 iteration count), while this validation happens on an
# unauthenticated route (creating a ManagedApp needs no login, see spec 7.2).
#
# The earlier approach was to read the private key header ourselves to decide "is it
# passphrase-protected" and skip parsing, which created a double-parser problem: "our
# home-made reader must always agree with net-ssh about the same bytes" -- a bypass
# really did occur (see the "prefix every line with -----" test below, which is the
# reproduced bypass). The current approach no longer predicts what net-ssh will do;
# instead it puts parsing in a subprocess and lets the parent process hold a hard
# timeout -- so the tests here assert that "wall-clock time falls within the timeout
# range" rather than "parsing is fast": the former actually verifies that the timeout
# really works, rather than the input happening to parse quickly this time.
class SshKeyValidatorTest < ActiveSupport::TestCase
  # Two fake subprocesses used only by tests, to verify just these two things in run_subprocess:
  # "writing stdin is also covered by the hard timeout" and "a child exiting early doesn't become an
  # uncaught Errno::EPIPE", without depending on any behavior of real net-ssh:
  #   - NeverReadsStdin: deliberately never reads stdin (simulating a stuck/malicious
  #     subprocess), to verify the parent's stdin.write doesn't hang the whole parent process.
  #   - ExitsImmediately: deliberately exits at once without reading stdin at all, to
  #     verify that when the parent's stdin.write hits an already-closed pipe, it just gets
  #     an Errno::EPIPE that is quietly swallowed rather than raised as an exception the caller sees.
  class NeverReadsStdin < SshKeyValidator
    private
      def command
        [ RbConfig.ruby, "-e", "sleep 100" ]
      end
  end

  class ExitsImmediately < SshKeyValidator
    private
      def command
        [ RbConfig.ruby, "-e", "exit 0" ]
      end
  end

  def real_key
    File.read(Rails.root.join("test/fake_host/id_ed25519"))
  end

  # A real passphrase-protected private key generated with `ssh-keygen -N <passphrase>`
  # (default 16 rounds of bcrypt). It is hardcoded as a literal in the test rather than
  # generated by running ssh-keygen so the test runs in any CI environment without
  # depending on an external command.
  def real_encrypted_key
    <<~KEY
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBtpKcxau
      yj+NdB+hJd1IWFAAAAGAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIOJPvz4TAssYb/bn
      UlIWbfr/NGKBIr21v5dLeflI4dzvAAAAkGjBap0O+bAxUNFZYQU5KLwruLvrfYv5Ii1hVm
      eXt1kyV8kmdsVHRDFSOJ96POf0vy6gWZedqKa0mPlVhxdwvqWnmlUIKL7VE2E8umlLWbfu
      n+RrLJfcrKng0hyw+lCYarSidsQJ6Y9a/2C+Y7seEW+22hcge9OHx2x/WK//2mLMTVoaMa
      qPZ8XB9TZeTnPq9g==
      -----END OPENSSH PRIVATE KEY-----
    KEY
  end

  test "真实私钥被判定可用，并给出指纹" do
    result = SshKeyValidator.call(real_key)

    assert result.ok?
    refute result.encrypted?
    assert_match(/\ASHA256:/, result.fingerprint)
  end

  test "真实带密码的私钥被判定为 encrypted，且判断很快（默认 16 轮 bcrypt，不是攻击输入）" do
    elapsed = monotonic_seconds { @result = SshKeyValidator.call(real_encrypted_key) }

    refute @result.ok?
    assert @result.encrypted?
    assert_operator elapsed, :<, 1.0
  end

  test "声明未知 key 类型的私钥被判定为不可用，而不是抛异常" do
    result = SshKeyValidator.call(openssh_key(type_name: "ssh-dss"))

    refute result.ok?
    refute result.encrypted?
  end

  test "攻击者构造的超大 bcrypt rounds 私钥在硬超时内被杀掉，而不是真的跑完" do
    # cipher=aes256-ctr / kdf=bcrypt, rounds is the uint32 max: if it really ran to
    # completion, the time needed is estimated in the "real bcrypt per-round cost" test
    # below (about 250 CPU-days). Here we give only a 0.3 second timeout and assert the
    # wall-clock time lands near this timeout (leaving margin for process creation/kill
    # overhead), rather than asserting "fast" -- only the former really proves the
    # timeout killed the subprocess, rather than the input happening to parse quickly this time.
    hostile = openssh_key(
      cipher: "aes256-ctr",
      kdf: "bcrypt",
      kdfopts: bcrypt_kdfopts(rounds: 0xFFFFFFFF),
      type_name: "ssh-dss"
    )

    elapsed = monotonic_seconds { with_safety_net { @result = SshKeyValidator.call(hostile, timeout: 0.3) } }

    refute @result.ok?
    assert_equal "timed_out", @result.error_class
    assert_operator elapsed, :<, 2.0, "应该在超时附近被杀掉，而不是真的跑完"
    assert_operator elapsed, :>=, 0.3
  end

  test "同一个超大 rounds 攻击，换成每行加 -----前缀的编码，依然在硬超时内被杀掉" do
    # This is the real bypass that was reproduced: the home-made OpenSSH header reader
    # filtered out lines starting with "-----", saw an empty body for this input, and
    # misjudged it as "not an OpenSSH private key" and let it through; while net-ssh
    # internally slices at fixed offsets and decodes with the lenient `unpack1("m")`
    # (which ignores non-base64 characters, including "-"), so the two saw exactly the same
    # decoded result (prefixing the base64 body line by line, `unpack1("m")` skips the "-"
    # characters as-is). Now that the "home-made reader" layer is gone, the only line of
    # defense is the subprocess timeout, so this malformed encoding should behave no
    # differently from the test above.
    hostile = openssh_key(
      cipher: "aes256-ctr",
      kdf: "bcrypt",
      kdfopts: bcrypt_kdfopts(rounds: 0xFFFFFFFF),
      type_name: "ssh-dss"
    )
    dashed = hostile.lines.map { |l|
      (l.start_with?("-----BEGIN") || l.start_with?("-----END")) ? l : "-----#{l.chomp}\n"
    }.join

    elapsed = monotonic_seconds { with_safety_net { @result = SshKeyValidator.call(dashed, timeout: 0.3) } }

    refute @result.ok?
    assert_equal "timed_out", @result.error_class
    assert_operator elapsed, :<, 2.0, "每行加 -----前缀不应该绕过硬超时"
  end

  test "攻击者构造的超大 iteration 的 PKCS#8 私钥在硬超时内被杀掉" do
    hostile = hostile_pkcs8(iterations: 200_000_000)

    elapsed = monotonic_seconds { with_safety_net { @result = SshKeyValidator.call(hostile, timeout: 0.3) } }

    refute @result.ok?
    assert_equal "timed_out", @result.error_class
    assert_operator elapsed, :<, 2.0, "应该在超时附近被杀掉，而不是真的跑完 PBKDF2"
  end

  test "真实 bcrypt 单轮耗时（用来对照上面两条测试确实没有真的跑完 KDF）" do
    require "bcrypt_pbkdf"
    elapsed = monotonic_seconds { BCryptPbkdf.key("x", "saltsaltsaltsalt", 48, 100) }
    per_round = elapsed / 100

    # 4294967295 rounds * per-round cost should far exceed the 2 seconds the two timeout
    # tests above allow -- that is, without the hard timeout those two tests would hang
    # for a very, very long time (about 250 CPU-days) instead of returning within 2 seconds.
    assert_operator per_round * 4_294_967_295, :>, 3600 * 24, "真实 KDF 應该比超时门槛慢好几个数量级"
  end

  test "畸形编码不会造成假拒绝：真实私钥换成不同的换行宽度/首尾空白依然能通过" do
    variants = {
      "无结尾换行" => real_key.chomp,
      "首尾多余空白" => "\n\n  #{real_key}  \n\n",
      "不规则换行宽度（每 40 字符换一行）" => rewrap(real_key, 40)
    }

    variants.each do |label, variant|
      result = SshKeyValidator.call(variant)
      assert result.ok?, "#{label}：应该仍然被判定为可用的私钥，实际 encrypted=#{result.encrypted?}"
    end
  end

  test "CRLF 行结尾的私钥被干净拒绝——这是 net-ssh 自身的行为（它的 BEGIN 标记严格匹配 \\n），不是本类引入的假拒绝" do
    result = SshKeyValidator.call(real_key.gsub("\n", "\r\n"))

    refute result.ok?
    refute result.encrypted?
  end

  # A payload to fill the pipe buffer: 16 KiB of private key content encodes to 98,316
  # bytes as JSON (reproducing the magnitude reported in the round 3 review), far above
  # the common 64KiB pipe buffer.
  def huge_value
    "\x01" * (16 * 1024)
  end

  test "父进程写 stdin 也受硬超时保护：子进程从不读 stdin 时，父进程不会被写操作卡住" do
    validator = NeverReadsStdin.new(huge_value, 0.5)

    elapsed = monotonic_seconds { with_safety_net { @result = validator.call } }

    refute @result.ok?
    assert_equal "timed_out", @result.error_class
    # Before this fix, what was measured here was 117.85 seconds (the parent really got stuck on
    # stdin.write and the hard timeout never took effect). Now it should land near the timeout.
    assert_operator elapsed, :<, 5.0, "stdin.write 应该跟别的 IO 一样受硬超时保护，不应该让父进程卡住"
  end

  test "子进程提前退出（完全不读 stdin）时，父进程写 stdin 不会抛出未处理的 Errno::EPIPE" do
    validator = ExitsImmediately.new(huge_value, 3.0)

    result = nil
    assert_nothing_raised do
      result = validator.call
    end

    refute result.ok?
  end

  test "校验结果不会把子进程内部的异常信息透出" do
    poison = openssh_key(type_name: "ssh-attacker-poison-marker")

    result = SshKeyValidator.call(poison)

    refute result.ok?
    # error_class should be just a class name, and must not contain the rejected raw bytes
    refute_includes result.error_class.to_s, "poison-marker"
  end

  private
    def monotonic_seconds
      t0 = Process.clock_gettime(Process::CLOCK_MONOTONIC)
      yield
      Process.clock_gettime(Process::CLOCK_MONOTONIC) - t0
    end

    # This is only a safety net for the test itself: if this class's hard timeout is ever
    # broken, this should make the test fail fast and exit, rather than hanging the whole
    # test process (and CI) on a bcrypt computation lasting hundreds of years. The reason
    # we can now count on Timeout.timeout working: before this round, the parent blocked
    # synchronously on a bare `stdin.write` system call, and that kind of block doesn't hit
    # the checkpoints where Ruby can safely interrupt a thread, so the outer
    # Timeout.timeout couldn't stop it (this is exactly the measurement in the round 3
    # review report, 117.85 seconds, where even Timeout.timeout(12) couldn't stop it).
    # Now writing stdin also happens in a thread, and the only thing the parent still waits
    # on is wait_thread.join(timeout) -- a Thread#join, which can be safely interrupted.
    def with_safety_net(seconds = 5)
      Timeout.timeout(seconds) { yield }
    rescue Timeout::Error
      flunk "硬超时看起来失效了：这次调用没有在 #{seconds} 秒安全网内返回"
    end

    def rewrap(pem, width)
      lines = pem.lines.map(&:chomp)
      head = lines.first
      tail = lines.last
      body = lines[1..-2].join
      wrapped = body.scan(/.{1,#{width}}/).join("\n")
      "#{head}\n#{wrapped}\n#{tail}\n"
    end

    def ssh_string(bytes)
      [ bytes.bytesize ].pack("N") + bytes
    end

    def bcrypt_kdfopts(rounds:)
      ssh_string("saltsaltsaltsalt") + [ rounds ].pack("N")
    end

    # Build a private key string that fits the openssh-key-v1 binary format, to test "does
    # parsing this input cause problems" as an attack surface without relying on ssh-keygen
    # (so the test runs in any CI environment, and can also express field combinations
    # ssh-keygen would never generate but an attacker can easily craft).
    def openssh_key(cipher: "none", kdf: "none", kdfopts: "", type_name: "ssh-dss", blocksize: 16)
      magic = "openssh-key-v1\0"
      check = "\x01\x02\x03\x04"
      fixed = check + check + ssh_string(type_name)

      # The private key block length must be a multiple of the cipher block size (net-ssh
      # checks this before decrypting), otherwise parsing is rejected for bad length before
      # it ever reaches the KDF -- and then we wouldn't be testing what we actually want
      # to test (whether the KDF really runs).
      pad = (-fixed.bytesize) % blocksize
      pad = blocksize if pad.zero?
      privsection = fixed + ("\x00" * pad)

      body = +""
      body << ssh_string(cipher)
      body << ssh_string(kdf)
      body << ssh_string(kdfopts)
      body << [ 1 ].pack("N")
      body << ssh_string("")
      body << ssh_string(privsection)

      raw = magic + body
      b64 = [ raw ].pack("m0").scan(/.{1,70}/).join("\n")
      "-----BEGIN OPENSSH PRIVATE KEY-----\n#{b64}\n-----END OPENSSH PRIVATE KEY-----\n"
    end

    # Build a PKCS#8 EncryptedPrivateKeyInfo (PBES2 + PBKDF2) whose iteration count can be
    # set freely -- this is another parsing branch that openssl/net-ssh takes (not the
    # OpenSSH private key format); the same shape of vulnerability (the attacker controls
    # how "expensive" the KDF is) exists on this branch too, and is unaffected by any of
    # the OpenSSH-related logic above.
    def hostile_pkcs8(iterations:, garbage_len: 64)
      salt = "S" * 16
      pbkdf2_params = OpenSSL::ASN1::Sequence([
        OpenSSL::ASN1::OctetString(salt),
        OpenSSL::ASN1::Integer(iterations)
      ])
      kdf_alg = OpenSSL::ASN1::Sequence([
        OpenSSL::ASN1::ObjectId("1.2.840.113549.1.5.12"), # pbkdf2
        pbkdf2_params
      ])
      iv = "I" * 16
      enc_scheme = OpenSSL::ASN1::Sequence([
        OpenSSL::ASN1::ObjectId("2.16.840.1.101.3.4.1.42"), # aes256-CBC
        OpenSSL::ASN1::OctetString(iv)
      ])
      pbes2_params = OpenSSL::ASN1::Sequence([ kdf_alg, enc_scheme ])
      enc_alg = OpenSSL::ASN1::Sequence([
        OpenSSL::ASN1::ObjectId("1.2.840.113549.1.5.13"), # pbes2
        pbes2_params
      ])
      encrypted_data = OpenSSL::ASN1::OctetString("G" * garbage_len)
      top = OpenSSL::ASN1::Sequence([ enc_alg, encrypted_data ])

      b64 = [ top.to_der ].pack("m0").scan(/.{1,64}/).join("\n")
      "-----BEGIN ENCRYPTED PRIVATE KEY-----\n#{b64}\n-----END ENCRYPTED PRIVATE KEY-----\n"
    end
end
