# The test environment is used exclusively to run your application's
# test suite. You never need to work with it otherwise. Remember that
# your test database is "scratch space" for the test suite and is wiped
# and recreated between test runs. Don't rely on the data there!

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # While tests run files are not watched, reloading is not necessary.
  config.enable_reloading = false

  # Eager loading loads your entire application. When running a single test locally,
  # this is usually not necessary, and can slow down your test suite. However, it's
  # recommended that you enable it in continuous integration systems to ensure eager
  # loading is working properly before deploying your code.
  config.eager_load = ENV["CI"].present?

  # Configure public file server for tests with cache-control for performance.
  config.public_file_server.headers = { "cache-control" => "public, max-age=3600" }

  # Show full error reports.
  config.consider_all_requests_local = true
  config.cache_store = :memory_store

  # Render exception templates for rescuable exceptions and raise for other exceptions.
  config.action_dispatch.show_exceptions = :rescuable

  # Disable request forgery protection in test environment.
  config.action_controller.allow_forgery_protection = false

  # Store uploaded files on the local file system in a temporary directory.
  config.active_storage.service = :test

  # Tell Action Mailer not to deliver emails to the real world.
  # The :test delivery method accumulates sent emails in the
  # ActionMailer::Base.deliveries array.
  config.action_mailer.delivery_method = :test

  # Set host to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "example.com" }

  # Print deprecation notices to the stderr.
  config.active_support.deprecation = :stderr

  # Fail on a missing translation instead of rendering "translation missing" on the page.
  #
  # Note how this works together with config.i18n.fallbacks = [ :en ]: when a Chinese translation is
  # missing, i18n silently falls back to English and does [not] trigger this raise. So this only
  # catches "missing in both Chinese and English", while "has Chinese but no English" is only caught
  # by LocaleSmokeTest actually rendering under :en. Neither can be dropped.
  config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  # config.action_view.annotate_rendered_view_with_filenames = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Fixed test-only Active Record encryption keys (generated by `bin/rails db:encryption:init`).
  # They only protect test data in the test database, and are of the same nature as the fake-host
  # SSH private key already committed to this repo (test/fake_host/id_ed25519): not production keys,
  # so having them on disk is harmless. CI injects them via env vars instead (see the test job in
  # .github/workflows/ci.yml); locally, `bin/rails test` falls back to the values here when those
  # env vars aren't set.
  config.active_record.encryption.primary_key = ENV.fetch("AR_ENCRYPTION_PRIMARY_KEY", "XPpmaOuyW56x2nZ4gfpW8EALrCI6UJvI")
  config.active_record.encryption.deterministic_key = ENV.fetch("AR_ENCRYPTION_DETERMINISTIC_KEY", "okmI399J9IkfdN2ckeGjcbTD6FkoxUiG")
  config.active_record.encryption.key_derivation_salt = ENV.fetch("AR_ENCRYPTION_KEY_DERIVATION_SALT", "XIZeEdvc2kyN0Epin1RzAzEPw1ADq8DH")
end
